name: Weekly Email Downloader

on:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  download_emails:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Download emails
        env:
          USERNAME: ${{ secrets.EMAIL_USERNAME }}
          PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python download_emails.py